// User types
export interface User {
  id: string;
  email: string;
  display_name: string;
  avatar_url?: string;
  preferences: UserPreferences;
}

export interface UserPreferences {
  default_budget_tier?: "budget" | "balanced" | "premium";
  default_pace?: "relaxed" | "moderate" | "active";
  interests?: string[];
}

// Trip types
export interface Trip {
  id: string;
  user_id: string;
  title: string;
  description?: string;
  start_date: string;
  end_date: string;
  status: "planning" | "confirmed" | "active" | "completed" | "cancelled";
  visibility: "private" | "shared" | "public";
  cover_image_url?: string;
  tags?: string[];
  destination_ids?: string[];
  budget?: TripBudget;
  itinerary?: ItineraryDay[];
  share_token?: string;
  shared_at?: string;
  created_at: string;
  updated_at: string;
}

export interface TripBudget {
  total: number;
  spent: number;
  currency: string;
  category_budgets?: Record<string, number>;
}

// Itinerary types
export interface ItineraryDay {
  day_number: number;
  date: string;
  title?: string;
  theme?: string;
  activities: Activity[];
  daily_budget?: DailyBudget;
  notes?: string;
}

export interface Activity {
  id?: string;
  time_slot: "morning" | "afternoon" | "evening";
  start_time: string;
  duration_minutes: number;
  name: string;
  type:
    | "attraction" | "restaurant" | "activity" | "transport"
    | "food" | "cafe" | "bar" | "foodie" | "market" | "shopping"
    | "cultural" | "museum" | "landmark" | "spa" | "wellness"
    | "entertainment" | "nightlife" | "nature" | "park" | "event"
    | string;  // Allow custom types from AI generation
  description: string;
  location: string;
  address?: string; // Full street address for map links
  coordinates?: {
    lat: number;
    lng: number;
  };
  estimated_cost: {
    amount: number;
    currency: string;
    tier: "free" | "budget" | "moderate" | "expensive";
  };
  tips: string[];
  booking_required: boolean;
  booking_url?: string;
  official_website?: string;
  image_url?: string;
}

export interface DailyBudget {
  total: number;
  breakdown: {
    activities: number;
    food: number;
    transport: number;
  };
}

// Generated itinerary from AI
export interface GeneratedItinerary {
  destination: {
    name: string;
    country: string;
    description: string;
    best_for: string[];
    weather_note: string;
  };
  days: ItineraryDay[];
  trip_summary: {
    total_estimated_cost: number;
    currency: string;
    highlights: string[];
    packing_suggestions: string[];
  };
  booking_links?: {
    flights: BookingLink[];
    hotels: BookingLink[];
  };
}

export interface BookingLink {
  provider: string;
  url: string;
  label: string;
}

// Travel segment for cached travel distances
export interface CachedTravelSegment {
  fromActivityId: string;
  toActivityId: string;
  mode: "WALKING" | "DRIVING" | "TRANSIT";
  distanceMeters: number;
  durationSeconds: number;
  distanceText: string;
  durationText: string;
}

// Cached travel data for a day
export interface CachedDayTravelData {
  dayNumber: number;
  segments: CachedTravelSegment[];
  totalDistanceMeters: number;
  totalDurationSeconds: number;
}

// Trip metadata stored in trip_meta JSONB column
// This data is generated by AI and preserved from the preview page
export interface TripMeta {
  weather_note?: string;           // Weather info for the destination
  highlights?: string[];           // Trip highlights (3-5 bullet points)
  booking_links?: {                // Affiliate booking links
    flights: BookingLink[];
    hotels: BookingLink[];
  };
  destination_best_for?: string[]; // Tags like "Culture", "Food", "Architecture"
  packing_suggestions?: string[];  // Suggested packing items
  // Cached travel distances to avoid API calls on repeat visits
  travel_distances?: CachedDayTravelData[];
  travel_distances_hash?: string;  // Hash of itinerary used to validate cache
}

// Trip vibe types (12 options: 8 practical + 4 fantasy/whimsical)
export type TripVibe =
  | "adventure"    // Outdoor activities, hiking, water sports, adrenaline
  | "cultural"     // Museums, heritage sites, local traditions, history
  | "foodie"       // Food markets, cooking classes, local cuisine, fine dining
  | "wellness"     // Spa, yoga, meditation, peaceful retreats
  | "romantic"     // Intimate experiences, sunset views, couple activities
  | "urban"        // City life, nightlife, architecture, trendy spots
  | "nature"       // Wildlife, national parks, wilderness, eco-tourism
  | "offbeat"      // Hidden gems, local secrets, non-touristy experiences
  | "wonderland"   // Alice in Wonderland vibes - quirky, whimsical, surreal spots
  | "movie-magic"  // Film locations, cinematic experiences, famous backdrops
  | "fairytale"    // Castles, enchanted forests, storybook villages
  | "retro";       // Vintage cafes, historic districts, nostalgic experiences

// Seasonal context for trip planning
export interface SeasonalContext {
  season: "spring" | "summer" | "autumn" | "winter";
  hemisphere: "northern" | "southern" | "tropical";
  avgTemp: { min: number; max: number };
  weather: string;
  holidays: string[];
  events: string[];
  crowdLevel: "low" | "moderate" | "high" | "peak";
}

// Vibe option for UI display
export interface VibeOption {
  id: TripVibe;
  label: string;
  emoji: string;
  color: string;
  description: string;
  details: string[];
  category: "practical" | "fantasy";
}

// User profile preferences that affect trip generation
export interface UserProfilePreferences {
  dietaryPreferences?: string[];  // e.g., ["vegetarian", "halal", "gluten-free"]
  travelStyles?: string[];        // e.g., ["adventure", "luxury", "solo"]
  accessibilityNeeds?: string[];  // e.g., ["wheelchair", "limited-mobility", "visual", "hearing"]
}

// Trip creation params
export interface TripCreationParams {
  destination: string;
  startDate: string;
  endDate: string;
  budgetTier: "budget" | "balanced" | "premium";
  pace: "relaxed" | "moderate" | "active";
  vibes: TripVibe[];  // Array of 1-3 vibes (ordered by priority)
  seasonalContext?: SeasonalContext;
  interests: string[];
  requirements?: string;
  // Profile-based preferences (fetched automatically from user profile)
  profilePreferences?: UserProfilePreferences;
}

// AI Assistant structured response types
export type AssistantCardType =
  | "activity_suggestion"  // Suggesting a new activity
  | "activity_replacement" // Replacing an existing activity
  | "activity_added"       // Confirmation that activity was added
  | "tip"                  // Quick tip or info
  | "comparison"           // Comparing multiple options
  | "confirmation"         // Action completed confirmation
  | "error";               // Error message

export interface AssistantActivityCard {
  type: "activity_suggestion" | "activity_added";
  activity: Activity;
  dayNumber?: number;
  reason?: string;
}

export interface AssistantReplacementCard {
  type: "activity_replacement";
  oldActivity: {
    id: string;
    name: string;
    type: Activity["type"];
  };
  newActivity: Activity;
  dayNumber: number;
  reason?: string;
  autoApplied?: boolean;  // Whether the change was automatically applied
}

export interface AssistantTipCard {
  type: "tip";
  icon: "lightbulb" | "warning" | "info" | "clock" | "money" | "weather";
  title: string;
  content: string;
}

export interface AssistantComparisonCard {
  type: "comparison";
  title: string;
  options: Array<{
    name: string;
    pros: string[];
    cons: string[];
    recommended?: boolean;
  }>;
}

export interface AssistantConfirmationCard {
  type: "confirmation";
  icon: "check" | "swap" | "plus" | "trash";
  title: string;
  description: string;
}

export interface AssistantErrorCard {
  type: "error";
  message: string;
}

export type AssistantCard =
  | AssistantActivityCard
  | AssistantReplacementCard
  | AssistantTipCard
  | AssistantComparisonCard
  | AssistantConfirmationCard
  | AssistantErrorCard;

export interface StructuredAssistantResponse {
  summary: string;           // Brief text summary (1-2 sentences max)
  cards?: AssistantCard[];   // Optional structured cards
  action?: {
    type: "replace_activity" | "add_activity" | "remove_activity" | "reorder";
    applied: boolean;        // Whether the action was auto-applied
    activityId?: string;     // For replace/remove actions
    dayNumber?: number;
    newActivity?: Activity;  // For add/replace actions
  };
}
