// Generated by scripts/translate-template-itineraries.mts; do not edit by hand.
import type { TemplateTranslation } from "../text";
import t0 from "./6c40f334-6ef5-4d59-839c-d4eeed8921e4.es.json";
import t1 from "./6c40f334-6ef5-4d59-839c-d4eeed8921e4.it.json";
import t2 from "./6c40f334-6ef5-4d59-839c-d4eeed8921e4.pt.json";
import t3 from "./b1a2c3d4-e5f6-4a5b-9c8d-7e6f5a4b3c2d.es.json";
import t4 from "./b1a2c3d4-e5f6-4a5b-9c8d-7e6f5a4b3c2d.it.json";
import t5 from "./b1a2c3d4-e5f6-4a5b-9c8d-7e6f5a4b3c2d.pt.json";
import t6 from "./c2a4acd9-c5be-4992-ae53-28aa599d2a02.es.json";
import t7 from "./c2a4acd9-c5be-4992-ae53-28aa599d2a02.it.json";
import t8 from "./c2a4acd9-c5be-4992-ae53-28aa599d2a02.pt.json";
import t9 from "./c2b3d4e5-f6a7-5b6c-0d9e-8f7a6b5c4d3e.es.json";
import t10 from "./c2b3d4e5-f6a7-5b6c-0d9e-8f7a6b5c4d3e.it.json";
import t11 from "./c2b3d4e5-f6a7-5b6c-0d9e-8f7a6b5c4d3e.pt.json";
import t12 from "./d3c4e5f6-a7b8-6c7d-1e0f-9a8b7c6d5e4f.es.json";
import t13 from "./d3c4e5f6-a7b8-6c7d-1e0f-9a8b7c6d5e4f.it.json";
import t14 from "./d3c4e5f6-a7b8-6c7d-1e0f-9a8b7c6d5e4f.pt.json";
import t15 from "./e4d5f6a7-b8c9-7d8e-2f1a-0b9c8d7e6f5a.es.json";
import t16 from "./e4d5f6a7-b8c9-7d8e-2f1a-0b9c8d7e6f5a.it.json";
import t17 from "./e4d5f6a7-b8c9-7d8e-2f1a-0b9c8d7e6f5a.pt.json";
import t18 from "./f5e6a7b8-c9d0-8e9f-3a2b-1c0d9e8f7a6b.es.json";
import t19 from "./f5e6a7b8-c9d0-8e9f-3a2b-1c0d9e8f7a6b.it.json";
import t20 from "./f5e6a7b8-c9d0-8e9f-3a2b-1c0d9e8f7a6b.pt.json";

export const TEMPLATE_ITINERARIES: Record<string, Partial<Record<"es" | "it" | "pt", TemplateTranslation>>> = {
  "6c40f334-6ef5-4d59-839c-d4eeed8921e4": { es: t0, it: t1, pt: t2 },
  "b1a2c3d4-e5f6-4a5b-9c8d-7e6f5a4b3c2d": { es: t3, it: t4, pt: t5 },
  "c2a4acd9-c5be-4992-ae53-28aa599d2a02": { es: t6, it: t7, pt: t8 },
  "c2b3d4e5-f6a7-5b6c-0d9e-8f7a6b5c4d3e": { es: t9, it: t10, pt: t11 },
  "d3c4e5f6-a7b8-6c7d-1e0f-9a8b7c6d5e4f": { es: t12, it: t13, pt: t14 },
  "e4d5f6a7-b8c9-7d8e-2f1a-0b9c8d7e6f5a": { es: t15, it: t16, pt: t17 },
  "f5e6a7b8-c9d0-8e9f-3a2b-1c0d9e8f7a6b": { es: t18, it: t19, pt: t20 },
};
