import type { Metadata, Viewport } from "next";
import { Fraunces, Source_Sans_3, Geist_Mono } from "next/font/google";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { GoogleAnalytics } from "@next/third-parties/google";
import { LocaleProvider } from "@/lib/locale";
import { PlaceCacheProvider } from "@/lib/context/PlaceCacheContext";
import { getLocale } from "next-intl/server";
import dynamic from "next/dynamic";
import { getNonce } from "@/lib/security/nonce";

// Dynamic import: moves SessionTracker + its dependencies (supabase, analytics, posthog/identify)
// to a separate chunk that loads after initial paint
const SessionTracker = dynamic(
  () => import("@/components/analytics/SessionTracker")
);
// NativeBoot: service-worker registration + Android back-button handler.
// Self-gates inside the Capacitor shell and on /trips/* paths — safe to
// always mount, costs ~0 on marketing pages.
const NativeBoot = dynamic(() => import("@/components/NativeBoot"));
// AffiliateScript: interaction-gated loader for the Travelpayouts script
// (was contributing to scroll-renderer-hang per LIVE_AUDIT F7).
const AffiliateScript = dynamic(() => import("@/components/AffiliateScript"));
import { PostHogProviderWrapper } from "./providers";
import {
  generateOrganizationSchema,
  generateWebSiteSchema,
  generateSoftwareApplicationSchema,
  jsonLdScriptProps,
} from "@/lib/seo/structured-data";
import "./globals.css";

// Display font for headings — warm editorial serif (variable font)
// Fraunces ships as a single woff2 covering 400/500/600/700 via the variable
// axis, so we get more weights than Playfair did at lower wire cost.
const fraunces = Fraunces({
  variable: "--font-display",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

// Body font - clean sans-serif
const sourceSans = Source_Sans_3({
  variable: "--font-source-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  display: "swap",
});

// Keep mono for code blocks
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  // Core metadata
  title: {
    default: "Free AI Trip Planner | Day-by-Day Itineraries in Minutes",
    template: "%s | MonkeyTravel",
  },
  description: "Plan your perfect trip with AI-generated day-by-day itineraries. Get Budget, Balanced, and Premium options tailored to your travel style. Create personalized travel plans in minutes!",
  keywords: ["travel app", "trip planner", "AI travel", "itinerary generator", "vacation planning", "MonkeyTravel", "travel AI", "trip planning app", "smart travel planner", "personalized itinerary"],
  authors: [{ name: "MonkeyTravel" }],
  creator: "MonkeyTravel",
  publisher: "MonkeyTravel",

  // Canonical URL
  metadataBase: new URL("https://monkeytravel.app"),
  alternates: {
    canonical: "https://monkeytravel.app",
  },

  // Open Graph for social sharing (Facebook, LinkedIn, Teams, WhatsApp, etc.)
  // Images are auto-generated by app/opengraph-image.tsx (file convention)
  openGraph: {
    title: "MonkeyTravel - AI-Powered Trip Planning",
    description: "Plan trips in minutes with AI-generated day-by-day itineraries. Budget, Balanced, and Premium options tailored to your travel style.",
    url: "https://monkeytravel.app",
    siteName: "MonkeyTravel",
    locale: "en_US",
    type: "website",
  },

  // Twitter/X Card — image auto-generated by app/twitter-image.tsx
  twitter: {
    card: "summary_large_image",
    title: "MonkeyTravel - AI-Powered Trip Planning",
    description: "Plan trips in minutes with AI-generated day-by-day itineraries",
    creator: "@monkeytravel",
  },

  // Icons configuration
  icons: {
    icon: [
      { url: "/favicon-16x16.png", sizes: "16x16", type: "image/png" },
      { url: "/favicon-32x32.png", sizes: "32x32", type: "image/png" },
    ],
    apple: [
      { url: "/apple-touch-icon.png", sizes: "180x180", type: "image/png" },
    ],
    other: [
      { rel: "icon", url: "/icon-192.png", sizes: "192x192", type: "image/png" },
      { rel: "icon", url: "/icon-512.png", sizes: "512x512", type: "image/png" },
    ],
  },

  // App manifest
  manifest: "/manifest.json",

  // Robots
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },

  // Verification - Google Search Console
  verification: {
    google: "KJqVVN_ZJWViJBugcmfFkOLX-ZDgACGJQTOLt1l2Mvo",
  },

  // App links for mobile
  appleWebApp: {
    capable: true,
    title: "MonkeyTravel",
    statusBarStyle: "default",
  },

  // Format detection
  formatDetection: {
    telephone: false,
  },

  // Category
  category: "travel",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
};

// Generate global structured data schemas
const organizationSchema = generateOrganizationSchema();
const webSiteSchema = generateWebSiteSchema();
const softwareApplicationSchema = generateSoftwareApplicationSchema();

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  // Per-request CSP nonce, generated in middleware.ts and exposed via the
  // `x-nonce` request header. Threaded into every inline <script> tag and
  // every <Script>-based loader so the nonce-based CSP doesn't reject
  // them in production. Undefined in dev (where CSP is not enforced) and
  // during static generation.
  const nonce = await getNonce();
  return (
    <html lang={locale}>
      <head>
        {/* Global Structured Data (JSON-LD) for SEO */}
        <script {...jsonLdScriptProps(organizationSchema, nonce)} />
        <script {...jsonLdScriptProps(webSiteSchema, nonce)} />
        <script {...jsonLdScriptProps(softwareApplicationSchema, nonce)} />

        {/* DNS prefetch for deferred third-party origins (preconnect removed —
            both scripts load after idle, so early connections expire unused) */}
        <link rel="dns-prefetch" href="https://emrldco.com" />
        <link rel="dns-prefetch" href="https://o4510503013122048.ingest.de.sentry.io" />
      </head>
      <body
        className={`${fraunces.variable} ${sourceSans.variable} ${geistMono.variable} antialiased`}
      >
        <PostHogProviderWrapper>
          <LocaleProvider>
            <PlaceCacheProvider>
              {children}
            </PlaceCacheProvider>
          </LocaleProvider>
        </PostHogProviderWrapper>
        <Analytics />
        <SpeedInsights />
        {/* Session tracking for retention analytics */}
        <SessionTracker />
        {/* Service worker (offline trips) + Android back-button handler */}
        <NativeBoot />
        {/* Google Analytics 4 - only load if measurement ID is configured.
            The `nonce` prop is forwarded to GA's inline gtag init script +
            the external gtag.js loader so both satisfy the nonce-based CSP. */}
        {process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID && (
          <GoogleAnalytics
            gaId={process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID}
            nonce={nonce}
          />
        )}
        {/* Travelpayouts Affiliate Network — interaction-gated loader.
            Was contributing to the deep-scroll renderer hang in
            LIVE_AUDIT F7 because long pages never go truly idle and
            lazyOnload would fire mid-scroll. */}
        <AffiliateScript nonce={nonce} />
      </body>
    </html>
  );
}
