import styles from "./HeroDoodleBackground.module.css";

/**
 * Layered doodle hero background, built from the decomposed brand art
 * (public/images/brand/hero/*, generated by design/build-hero-assets.mjs).
 *
 * - Desktop: full 1525x1031 scenery base (object-fit: cover) + free-floating sky sprites.
 * - Mobile (<768px): a dedicated portrait recomposition (base-mobile.webp, 750x1624) anchored
 *   to the bottom — no centre-crop of landscape art — with repositioned sprites.
 * - All motion is transform/opacity-only CSS, disabled under prefers-reduced-motion.
 * - Total art weight ~131 KB WebP across 16 files; sprites are lazy, base is eager.
 *
 * Server component: no client JS. Drop inside a relatively-positioned hero section:
 *   <section className="relative ..."><HeroDoodleBackground /> ...content (relative z-10)</section>
 *
 * `layout` describes the hero the art sits behind, because that decides where
 * the empty space is:
 * - "split" (homepage): copy left, phone right. The sky and the mascot live in
 *   the gap between them.
 * - "centered" (landing pages): one centred copy column that runs the full
 *   width. There is no gap, so the mascot and the mid-sky doodles would paint
 *   straight over the headline — only the scenery and a corner sun remain.
 */

const HERO = "/images/brand/hero";

export default function HeroDoodleBackground({
  layout = "split",
}: {
  layout?: "split" | "centered";
}) {
  return (
    <div
      className={layout === "centered" ? `${styles.root} ${styles.centered}` : styles.root}
      aria-hidden="true"
    >
      {/* static scenery: browser downloads only the matching source.

          The `width`/`height` on <source> are load-bearing, not decoration.
          The two artworks are art-directed crops with very different shapes —
          desktop 1525x1031 (aspect 1.479, landscape), mobile 750x1624 (aspect
          0.462, portrait) — and on mobile `.base` is `height: auto` anchored to
          the bottom, so its height comes ENTIRELY from the intrinsic aspect
          ratio.

          Without dimensions on the <source>, the browser falls back to the
          <img> attributes, reserves a LANDSCAPE box for a PORTRAIT image, and
          then resizes it on load. Measured in a Lighthouse trace: one shift,
          score 0.5135, the element growing 210px -> 704px with its bottom
          pinned — which was the whole of the homepage's CLS failure (field p75
          0.57, the only Core Web Vital not passing).

          <source> takes width/height precisely so an art-directed picture can
          declare its own aspect ratio. Keep these in step with the files. */}
      <picture>
        <source
          media="(max-width: 767.98px)"
          srcSet={`${HERO}/base-mobile.webp`}
          width={750}
          height={1624}
        />
        <img
          src={`${HERO}/base-desktop.webp`} width={1525} height={1031}
          alt=""
          className={styles.base}
          draggable={false}
          decoding="async"
        />
      </picture>

      {/* sun: rays rotate around the disc, the smiley stays upright */}
      <div className={`${styles.sprite} ${styles.sunGroup}`}>
        <img src={`${HERO}/sun-rays.webp`} width={164} height={164} alt="" className={styles.sunRays} draggable={false} loading="lazy" />
        <img src={`${HERO}/sun-disc.webp`} width={100} height={100} alt="" className={styles.sunDisc} draggable={false} loading="lazy" />
      </div>

      {/* clouds */}
      <img src={`${HERO}/cloud-2.webp`} width={67} height={39} alt="" className={`${styles.sprite} ${styles.cloud2}`} draggable={false} loading="lazy" />
      <img src={`${HERO}/cloud-3.webp`} width={158} height={80} alt="" className={`${styles.sprite} ${styles.cloud3}`} draggable={false} loading="lazy" />

      {/* plane + dashed travel path stay glued together inside one group */}
      <div className={`${styles.sprite} ${styles.planeGroup}`}>
        <img src={`${HERO}/trail.webp`} width={252} height={141} alt="" className={styles.trail} draggable={false} loading="lazy" />
        <img src={`${HERO}/plane.webp`} width={164} height={88} alt="" className={styles.plane} draggable={false} loading="lazy" />
      </div>

      {/* cloud-1, the balloon, the teal dot and sparkle-4 exist in the source
          art but not in the composition — the module stylesheet says why. */}

      {/* sparkles twinkle on staggered delays */}
      <img src={`${HERO}/sparkle-1.webp`} width={38} height={40} alt="" className={`${styles.sprite} ${styles.sp1}`} draggable={false} loading="lazy" />
      <img src={`${HERO}/sparkle-2.webp`} width={31} height={33} alt="" className={`${styles.sprite} ${styles.sp2}`} draggable={false} loading="lazy" />
      <img src={`${HERO}/sparkle-3.webp`} width={25} height={26} alt="" className={`${styles.sprite} ${styles.sp3}`} draggable={false} loading="lazy" />

      {/* mascot: desktop only (hidden <768px via CSS), AVIF with WebP fallback */}
      <picture>
        <source
          type="image/avif"
          srcSet={`${HERO}/mascot-480.avif 480w, ${HERO}/mascot-645.avif 645w`}
          sizes="300px"
        />
        <img
          src={`${HERO}/mascot-480.webp`} width={480} height={997}
          srcSet={`${HERO}/mascot-480.webp 480w, ${HERO}/mascot-645.webp 645w`}
          sizes="300px"
          alt=""
          className={styles.mascot}
          draggable={false}
          decoding="async"
        />
      </picture>
    </div>
  );
}
