import styles from "./HeroDoodleBackground.module.css";

/**
 * Layered doodle hero background, built from the decomposed brand art
 * (public/images/brand/hero/*, generated by design/build-hero-assets.mjs).
 *
 * - Desktop: full 1525x1031 scenery base (object-fit: cover) + free-floating sky sprites.
 * - Mobile (<768px): a dedicated portrait recomposition (base-mobile.webp, 750x1624) anchored
 *   to the bottom — no centre-crop of landscape art — with repositioned sprites.
 * - All motion is transform/opacity-only CSS, disabled under prefers-reduced-motion.
 * - Total art weight ~131 KB WebP across 16 files; sprites are lazy, base is eager.
 *
 * Server component: no client JS. Drop inside a relatively-positioned hero section:
 *   <section className="relative ..."><HeroDoodleBackground /> ...content (relative z-10)</section>
 */

const HERO = "/images/brand/hero";

export default function HeroDoodleBackground() {
  return (
    <div className={styles.root} aria-hidden="true">
      {/* static scenery: browser downloads only the matching source */}
      <picture>
        <source media="(max-width: 767.98px)" srcSet={`${HERO}/base-mobile.webp`} />
        <img
          src={`${HERO}/base-desktop.webp`}
          alt=""
          className={styles.base}
          draggable={false}
          decoding="async"
        />
      </picture>

      {/* sun: rays rotate around the disc, the smiley stays upright */}
      <div className={`${styles.sprite} ${styles.sunGroup}`}>
        <img src={`${HERO}/sun-rays.webp`} alt="" className={styles.sunRays} draggable={false} loading="lazy" />
        <img src={`${HERO}/sun-disc.webp`} alt="" className={styles.sunDisc} draggable={false} loading="lazy" />
      </div>

      {/* clouds */}
      <img src={`${HERO}/cloud-1.webp`} alt="" className={`${styles.sprite} ${styles.cloud1}`} draggable={false} loading="lazy" />
      <img src={`${HERO}/cloud-2.webp`} alt="" className={`${styles.sprite} ${styles.cloud2}`} draggable={false} loading="lazy" />
      <img src={`${HERO}/cloud-3.webp`} alt="" className={`${styles.sprite} ${styles.cloud3}`} draggable={false} loading="lazy" />

      {/* plane + dashed travel path stay glued together inside one group */}
      <div className={`${styles.sprite} ${styles.planeGroup}`}>
        <img src={`${HERO}/trail.webp`} alt="" className={styles.trail} draggable={false} loading="lazy" />
        <img src={`${HERO}/plane.webp`} alt="" className={styles.plane} draggable={false} loading="lazy" />
      </div>

      <img src={`${HERO}/balloon.webp`} alt="" className={`${styles.sprite} ${styles.balloon}`} draggable={false} loading="lazy" />
      <img src={`${HERO}/dot-teal.webp`} alt="" className={`${styles.sprite} ${styles.dot}`} draggable={false} loading="lazy" />

      {/* sparkles twinkle on staggered delays */}
      <img src={`${HERO}/sparkle-1.webp`} alt="" className={`${styles.sprite} ${styles.sp1}`} draggable={false} loading="lazy" />
      <img src={`${HERO}/sparkle-2.webp`} alt="" className={`${styles.sprite} ${styles.sp2}`} draggable={false} loading="lazy" />
      <img src={`${HERO}/sparkle-3.webp`} alt="" className={`${styles.sprite} ${styles.sp3}`} draggable={false} loading="lazy" />
      <img src={`${HERO}/sparkle-4.webp`} alt="" className={`${styles.sprite} ${styles.sp4}`} draggable={false} loading="lazy" />

      {/* mascot: desktop only (hidden <768px via CSS), AVIF with WebP fallback */}
      <picture>
        <source
          type="image/avif"
          srcSet={`${HERO}/mascot-480.avif 480w, ${HERO}/mascot-645.avif 645w`}
          sizes="16vw"
        />
        <img
          src={`${HERO}/mascot-480.webp`}
          srcSet={`${HERO}/mascot-480.webp 480w, ${HERO}/mascot-645.webp 645w`}
          sizes="16vw"
          alt=""
          className={styles.mascot}
          draggable={false}
          decoding="async"
        />
      </picture>
    </div>
  );
}
