import { NextRequest } from "next/server";
import { getAuthenticatedUser } from "@/lib/api/auth";
import { errors, apiSuccess } from "@/lib/api/response-wrapper";
import { isExploreUgcEnabled } from "@/lib/explore/flag";
import { captureServerEvent } from "@/lib/posthog/server";
import { generateActivityId } from "@/lib/utils/activity-id";
import { scheduleTripNotifications } from "@/lib/notifications/scheduling";
import type { ItineraryDay, Activity } from "@/types";

/**
 * POST /api/trips/[id]/fork
 *
 * Clone a public trip into the caller's account as a NEW private trip.
 * The new trip retains parent_trip_id so we can:
 *   - Increment the parent's fork_count (algorithmic Editor's Picks signal)
 *   - Show provenance ("forked from Anonymous traveler's Tokyo trip")
 *
 * Body:
 *   - startDate (optional ISO date) — when the forked trip starts.
 *     Defaults to (today + 30 days). Itinerary dates are remapped from
 *     the source.
 *
 * Why not just send the user to the wizard pre-filled? Because the
 * value of forking is *getting the actual itinerary*. The wizard would
 * regenerate from scratch — different activities, different vibe. Fork
 * preserves the exact trip the user clicked "use this" on; the user
 * can then customize it via /trips/[newId].
 *
 * The fork lands as `visibility=private` by default. The user can
 * re-publish it via /publish, which creates an attribution loop:
 * parent → fork → fork-of-fork.
 */

type RouteCtx = { params: Promise<{ id: string }> };

export async function POST(request: NextRequest, { params }: RouteCtx) {
  if (!isExploreUgcEnabled()) return errors.notFound("Not Found");

  const { id: sourceTripId } = await params;
  if (!sourceTripId) return errors.badRequest("Trip id required");

  const { user, supabase, errorResponse } = await getAuthenticatedUser();
  if (errorResponse) return errorResponse;

  // Body is optional — clients can POST with no body to use defaults.
  let startDate: string | null = null;
  try {
    const body = await request.json().catch(() => ({}));
    if (typeof body?.startDate === "string") startDate = body.startDate;
  } catch {
    // empty body is fine
  }

  // Validate user-supplied startDate before defaulting.
  // Bad input (empty string, malformed, far-future) would otherwise
  // produce "Invalid Date" downstream and surface as a 500 RangeError.
  if (startDate !== null) {
    const parsed = new Date(startDate);
    if (isNaN(parsed.getTime())) {
      return errors.badRequest("Invalid startDate");
    }
    const now = Date.now();
    if (
      parsed.getTime() < now - 365 * 24 * 3600 * 1000 ||
      parsed.getTime() > now + 5 * 365 * 24 * 3600 * 1000
    ) {
      return errors.badRequest("startDate out of reasonable range");
    }
  }

  // Default: 30 days from today.
  if (!startDate) {
    const d = new Date();
    d.setDate(d.getDate() + 30);
    startDate = d.toISOString().split("T")[0];
  }

  // Pull the source trip. Must be public + not hidden.
  const { data: src, error: srcErr } = await supabase
    .from("trips")
    .select("*")
    .eq("id", sourceTripId)
    .single();

  if (srcErr || !src) return errors.notFound("Trip not found");
  if (src.visibility !== "public" || src.is_hidden) {
    return errors.notFound("Trip not found");
  }

  // Walk activities, regenerate IDs (so the new trip doesn't collide
  // with the source on activity-level interactions like votes), and
  // remap day dates from the new start.
  const start = new Date(startDate + "T00:00:00");
  const sourceDays: ItineraryDay[] = src.itinerary ?? [];
  const adjustedItinerary: ItineraryDay[] = sourceDays.map((day, idx) => {
    const d = new Date(start);
    d.setDate(d.getDate() + idx);
    return {
      ...day,
      date: d.toISOString().split("T")[0],
      activities: day.activities.map((a: Activity) => ({
        ...a,
        id: generateActivityId(),
      })),
    };
  });

  const durationDays = adjustedItinerary.length || 1;
  const end = new Date(start);
  end.setDate(end.getDate() + durationDays - 1);

  // The cloned row. Note we DROP fields that shouldn't transfer:
  //   - id, created_at, shared_at, share_token (regenerated by DB)
  //   - all engagement counters (start at 0)
  //   - author_display_name, author_note, is_editors_pick (per-fork)
  //   - is_template (forks aren't templates by default)
  //   - reported_count, is_hidden, submitted_to_trending_at
  const newRow = {
    user_id: user.id,
    title: src.title,
    description: src.description,
    start_date: startDate,
    end_date: end.toISOString().split("T")[0],
    status: "planning",
    visibility: "private", // owner explicitly opts in via /publish later
    itinerary: adjustedItinerary,
    cover_image_url: src.cover_image_url,
    budget: src.budget,
    tags: src.tags,
    trip_meta: src.trip_meta,
    packing_list: src.packing_list,
    parent_trip_id: src.id, // <-- attribution
  };

  const { data: created, error: insertErr } = await supabase
    .from("trips")
    .insert(newRow)
    .select("id")
    .single();

  if (insertErr || !created) {
    return errors.internal("Failed to fork trip", "trips.insert");
  }

  // Bump the source's fork counter + trending score (atomic RPC).
  const { error: rpcErr } = await supabase.rpc("increment_trip_fork_count", {
    p_trip_id: src.id,
  });
  if (rpcErr) {
    console.error("[trip-fork] counter drift after insert:", rpcErr);
  }

  void captureServerEvent(user.id, "explore_trip_forked", {
    source_trip_id: src.id,
    new_trip_id: created.id,
    start_date: startDate,
  });

  // Fire-and-forget enqueue of the 5-slot pre-trip cascade for the
  // forked trip. Gated by NEXT_PUBLIC_CALENDAR_EXPORT_ENABLED;
  // failures log + Sentry-capture but never re-throw — a fork
  // succeeding is more important than its reminder queue.
  void scheduleTripNotifications({ tripId: created.id, userId: user.id });

  return apiSuccess({
    newTripId: created.id,
    redirectTo: `/trips/${created.id}`,
  });
}
