/**
 * Log the E2E fixture accounts in through the REAL login UI and save a
 * Playwright storageState for each.
 *
 * Why drive the form rather than mint a session with the service key: the app
 * uses @supabase/ssr cookie sessions, whose cookie name, chunking and encoding
 * are an implementation detail that changes between versions. Hand-forging
 * those cookies produces a harness that breaks for reasons unrelated to the
 * code under test. Driving the form gets exactly the session a real user has —
 * and exercises login itself on the way through.
 *
 * The credentials are generated by scripts/e2e-fixtures.mts for throwaway
 * accounts on a non-routable domain, and live only in .auth/ (self-ignored).
 *
 *   npx tsx scripts/e2e-fixtures.mts --seed
 *   npx tsx scripts/e2e-login.mts                       # -> prod
 *   BASE_URL=http://localhost:3000 npx tsx scripts/e2e-login.mts
 */

import { chromium } from "@playwright/test";
import { existsSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const AUTH_DIR = join(ROOT, ".auth");
const MANIFEST = join(AUTH_DIR, "e2e-fixtures.json");
const BASE_URL = process.env.BASE_URL ?? "https://monkeytravel.app";

if (!existsSync(MANIFEST)) {
  console.error(`No ${MANIFEST}. Run: npx tsx scripts/e2e-fixtures.mts --seed`);
  process.exit(1);
}

type Manifest = {
  users: Record<string, { id: string; email: string; password: string; name: string }>;
};
const manifest: Manifest = JSON.parse(readFileSync(MANIFEST, "utf8"));

const browser = await chromium.launch();
let failures = 0;

for (const [role, u] of Object.entries(manifest.users)) {
  // A fresh context per role: reusing one would carry the previous session's
  // cookies and silently save the wrong user's state.
  const ctx = await browser.newContext();
  const page = await ctx.newPage();
  try {
    await page.goto(`${BASE_URL}/auth/login`, { waitUntil: "domcontentloaded" });

    // Wait for hydration before touching anything. Filling a server-rendered
    // input and letting React mount over it afterwards clears the value, and
    // the failure looks like a wrong password: the form submits EMPTY and the
    // browser shows "Please fill out this field" over an untouched box.
    await page.waitForLoadState("networkidle").catch(() => {});
    await page.locator("#email").waitFor({ state: "visible", timeout: 15_000 });

    // The consent banner overlays the form and blocks the submit click.
    // Decline rather than remove it — removing a React-managed node crashes
    // the app with React #185, which looks exactly like a production bug.
    // It is client-rendered, so it can arrive AFTER the form: give it long
    // enough to appear rather than racing it.
    const essential = page.getByRole("button", { name: /essential only|only essential|rifiuta|solo esencial|essenziali|apenas essenciais/i });
    if (await essential.isVisible({ timeout: 10_000 }).catch(() => false)) {
      await essential.click();
      await essential.waitFor({ state: "hidden", timeout: 5_000 }).catch(() => {});
    }

    await page.fill("#email", u.email);
    await page.fill("#password", u.password);

    // Assert the values actually stuck. Submitting an empty form produces a
    // 30s navigation timeout whose message says nothing about the real cause.
    if ((await page.inputValue("#email")) !== u.email) {
      await page.fill("#email", u.email);
      await page.fill("#password", u.password);
    }
    if ((await page.inputValue("#email")) !== u.email) {
      throw new Error("email field would not hold its value (hydration reset?)");
    }

    await page.click('button[type="submit"]');

    // Success is a navigation away from /auth/login. Assert on that rather
    // than on a toast, which is timing-dependent.
    await page.waitForURL((url) => !url.pathname.includes("/auth/login"), {
      timeout: 30_000,
    });

    const out = join(AUTH_DIR, `${role}.json`);
    await ctx.storageState({ path: out });

    // A storageState with no Supabase auth cookie is a silent failure: the
    // file exists, the tests run, and every request is anonymous.
    const saved = JSON.parse(readFileSync(out, "utf8"));
    const hasAuth = (saved.cookies ?? []).some(
      (c: { name: string }) => c.name.startsWith("sb-") && c.name.includes("auth-token")
    );
    if (!hasAuth) throw new Error("no sb-*-auth-token cookie in saved state");

    console.log(`  ok    ${role.padEnd(6)} ${u.email} -> .auth/${role}.json`);
  } catch (err) {
    failures++;
    console.error(`  FAIL  ${role.padEnd(6)} ${u.email}: ${(err as Error).message}`);
    await page
      .screenshot({ path: join(AUTH_DIR, `login-fail-${role}.png`) })
      .catch(() => {});
  } finally {
    await ctx.close();
  }
}

await browser.close();
process.exit(failures ? 1 : 0);
