"use client";

import { useState, useRef, useEffect } from "react";
import type { ItineraryDay, TripMeta } from "@/types";
// Types only (zero bundle impact) - functions loaded dynamically on demand
import type { PremiumTripForExport } from "@/lib/export/pdf";
import { downloadICS } from "@/lib/export/calendar";
import { useTranslations } from "next-intl";

// Lazy loaders for PDF export (~75KB saved from initial bundle)
const lazyLoadPdfExport = () => import("@/lib/export/pdf");
const lazyLoadPremiumPdfExport = () => import("@/lib/export/pdf/index");

interface ExportMenuProps {
  trip: {
    title: string;
    description?: string;
    startDate: string;
    endDate: string;
    budget?: { total: number; currency: string } | null;
    itinerary: ItineraryDay[];
  };
  // Optional props for premium PDF
  destination?: string;
  meta?: TripMeta;
  coverImageUrl?: string;
  galleryPhotos?: { url: string; thumbnailUrl: string }[];
}

export default function ExportMenu({ trip, destination, meta, coverImageUrl, galleryPhotos }: ExportMenuProps) {
  const t = useTranslations('common.export');
  const [isOpen, setIsOpen] = useState(false);
  const [isExporting, setIsExporting] = useState<"pdf" | "premium-pdf" | "ics" | null>(null);
  const [exportProgress, setExportProgress] = useState<{ step: string; progress: number } | null>(null);
  const menuRef = useRef<HTMLDivElement>(null);

  // Close menu when clicking outside
  useEffect(() => {
    function handleClickOutside(event: MouseEvent) {
      if (menuRef.current && !menuRef.current.contains(event.target as Node)) {
        setIsOpen(false);
      }
    }

    document.addEventListener("mousedown", handleClickOutside);
    return () => {
      document.removeEventListener("mousedown", handleClickOutside);
    };
  }, []);

  const handleExportPDF = async () => {
    setIsExporting("pdf");
    try {
      // Dynamically load PDF export on first use (~75KB)
      const { downloadPDF } = await lazyLoadPdfExport();
      await downloadPDF(trip);
    } catch (error) {
      console.error("Error exporting PDF:", error);
    } finally {
      setIsExporting(null);
      setIsOpen(false);
    }
  };

  const handleExportPremiumPDF = async () => {
    setIsExporting("premium-pdf");
    setExportProgress({ step: "Starting...", progress: 0 });

    try {
      // Dynamically load premium PDF export on first use
      const { downloadPremiumPDF } = await lazyLoadPremiumPdfExport();

      // Build the premium trip data
      const premiumTrip: PremiumTripForExport = {
        title: trip.title,
        description: trip.description,
        destination: destination || trip.title.replace(/ Trip$/, ""),
        startDate: trip.startDate,
        endDate: trip.endDate,
        budget: trip.budget,
        itinerary: trip.itinerary,
        meta: meta,
        coverImageUrl: coverImageUrl,
        galleryPhotos: galleryPhotos,
      };

      await downloadPremiumPDF(premiumTrip, (step, progress) => {
        setExportProgress({ step, progress });
      });
    } catch (error) {
      console.error("Error exporting premium PDF:", error);
    } finally {
      setIsExporting(null);
      setExportProgress(null);
      setIsOpen(false);
    }
  };

  const handleExportICS = () => {
    setIsExporting("ics");
    try {
      downloadICS(trip);
    } catch (error) {
      console.error("Error exporting ICS:", error);
    } finally {
      setIsExporting(null);
      setIsOpen(false);
    }
  };

  const handleGoogleCalendar = () => {
    // Create Google Calendar event for the first activity
    const firstDay = trip.itinerary[0];
    const firstActivity = firstDay?.activities[0];

    if (firstActivity && firstDay) {
      const startDate = firstDay.date.replace(/-/g, "");
      const endDate = trip.endDate.replace(/-/g, "");

      const params = new URLSearchParams({
        action: "TEMPLATE",
        text: trip.title,
        dates: `${startDate}/${endDate}`,
        details: `Trip itinerary generated by MonkeyTravel\n\n${trip.description || ""}`,
      });

      window.open(`https://calendar.google.com/calendar/render?${params.toString()}`, "_blank");
    }

    setIsOpen(false);
  };

  return (
    <div className="relative" ref={menuRef}>
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="flex items-center gap-2 px-3 py-2 rounded-lg text-sm font-medium bg-slate-100 text-slate-600 hover:bg-slate-200 transition-colors"
      >
        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
        </svg>
        {t('title')}
        <svg className={`w-3 h-3 transition-transform ${isOpen ? "rotate-180" : ""}`} fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
        </svg>
      </button>

      {isOpen && (
        <div className="absolute right-0 mt-2 w-64 bg-white border border-slate-200 rounded-xl shadow-lg py-2 z-20">
          <div className="px-3 py-2 border-b border-slate-100">
            <span className="text-xs font-medium text-slate-500 uppercase tracking-wider">
              {t('download')}
            </span>
          </div>

          {/* Premium PDF - Hidden for now, code preserved for future improvements */}

          {/* PDF */}
          <button
            onClick={handleExportPDF}
            disabled={isExporting === "pdf"}
            className="w-full flex items-center gap-3 px-3 py-2.5 text-left text-sm text-slate-700 hover:bg-slate-50 transition-colors disabled:opacity-50"
          >
            {isExporting === "pdf" ? (
              <svg className="w-5 h-5 animate-spin text-slate-400" fill="none" viewBox="0 0 24 24">
                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
              </svg>
            ) : (
              <svg className="w-5 h-5 text-slate-400" fill="currentColor" viewBox="0 0 24 24">
                <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8l-6-6z" />
                <path d="M14 2v6h6M9 13h6M9 17h6" stroke="white" strokeWidth="1.5" fill="none" />
              </svg>
            )}
            <div>
              <div className="font-medium">{t('pdfItinerary')}</div>
              <div className="text-xs text-slate-500">{t('pdfDescription')}</div>
            </div>
          </button>

          <button
            onClick={handleExportICS}
            disabled={isExporting === "ics"}
            className="w-full flex items-center gap-3 px-3 py-2.5 text-left text-sm text-slate-700 hover:bg-slate-50 transition-colors disabled:opacity-50"
          >
            {isExporting === "ics" ? (
              <svg className="w-5 h-5 animate-spin text-slate-400" fill="none" viewBox="0 0 24 24">
                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
              </svg>
            ) : (
              <svg className="w-5 h-5 text-blue-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
              </svg>
            )}
            <div>
              <div className="font-medium">{t('calendarFile')}</div>
              <div className="text-xs text-slate-500">{t('calendarDescription')}</div>
            </div>
          </button>

          <div className="px-3 py-2 border-t border-slate-100 mt-1">
            <span className="text-xs font-medium text-slate-500 uppercase tracking-wider">
              {t('addToCalendar')}
            </span>
          </div>

          <button
            onClick={handleGoogleCalendar}
            className="w-full flex items-center gap-3 px-3 py-2.5 text-left text-sm text-slate-700 hover:bg-slate-50 transition-colors"
          >
            <svg className="w-5 h-5" viewBox="0 0 24 24">
              <path fill="#4285F4" d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z" />
              <path fill="#34A853" d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z" />
              <path fill="#FBBC05" d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z" />
              <path fill="#EA4335" d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z" />
            </svg>
            <div>
              <div className="font-medium">{t('googleCalendar')}</div>
              <div className="text-xs text-slate-500">{t('googleCalendarDescription')}</div>
            </div>
          </button>

          <a
            href={`webcal://monkeytravel.app/api/export/calendar/${trip.title}`}
            className="w-full flex items-center gap-3 px-3 py-2.5 text-left text-sm text-slate-700 hover:bg-slate-50 transition-colors"
            onClick={() => setIsOpen(false)}
          >
            <svg className="w-5 h-5 text-slate-700" fill="currentColor" viewBox="0 0 24 24">
              <path d="M18.71 19.5c-.83 1.24-1.71 2.45-3.05 2.47-1.34.03-1.77-.79-3.29-.79-1.53 0-2 .77-3.27.82-1.31.05-2.3-1.32-3.14-2.53C4.25 17 2.94 12.45 4.7 9.39c.87-1.52 2.43-2.48 4.12-2.51 1.28-.02 2.5.87 3.29.87.78 0 2.26-1.07 3.81-.91.65.03 2.47.26 3.64 1.98-.09.06-2.17 1.28-2.15 3.81.03 3.02 2.65 4.03 2.68 4.04-.03.07-.42 1.44-1.38 2.83M13 3.5c.73-.83 1.94-1.46 2.94-1.5.13 1.17-.34 2.35-1.04 3.19-.69.85-1.83 1.51-2.95 1.42-.15-1.15.41-2.35 1.05-3.11z" />
            </svg>
            <div>
              <div className="font-medium">{t('appleCalendar')}</div>
              <div className="text-xs text-slate-500">{t('appleCalendarDescription')}</div>
            </div>
          </a>
        </div>
      )}
    </div>
  );
}
