-- =====================================================
-- Anonymous Activity Votes
-- =====================================================
-- Unlocks the public collaborative use case on /shared/[token]: anyone with
-- the share link can thumbs-up/thumbs-down individual activities without
-- signing up. This is intentionally distinct from the authenticated
-- `activity_votes` table (love/flexible/concerns/no, weighted consensus),
-- which only covers logged-in collaborators. Both coexist.
--
-- Dedupe key is a cookie-issued opaque id, not the user (there is no user).
-- Anti-abuse is best-effort — clearing cookies lets you vote again. We accept
-- that trade-off because the alternative (forcing signup) defeats the point.
--
-- All writes go through the service-role API route at
-- `/api/shared/[token]/vote`, which validates the share_token before
-- accepting the vote. RLS therefore blocks anon INSERT/UPDATE/DELETE entirely
-- and only exposes SELECT (the data is public — viewers can see tallies).
-- =====================================================

CREATE TABLE IF NOT EXISTS public.anonymous_activity_votes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- The trip being voted on. Cascade so deleting a trip cleans up its votes.
  trip_id UUID NOT NULL REFERENCES public.trips(id) ON DELETE CASCADE,

  -- The activity inside trips.itinerary JSONB. Not a FK — activities live
  -- inside the JSONB blob, identified by a per-activity nanoid generated by
  -- `ensureActivityIds()`. If the owner restructures the itinerary, stale
  -- votes are simply orphaned (no FK to break).
  activity_id TEXT NOT NULL,

  -- Proves the voter had access via a shared link at the time of voting.
  -- Recorded for audit/abuse-investigation. We don't reject on mismatch at
  -- query time — the API route enforces token→trip resolution before insert.
  share_token UUID NOT NULL,

  -- Cookie-issued opaque id (nanoid). The dedupe key. Same browser revoting
  -- on the same activity updates the existing row instead of inserting.
  voter_cookie_id TEXT NOT NULL,

  -- Optional friendly name ("Sarah") so the trip owner can see WHO voted,
  -- not just an opaque cookie id. Collected via inline prompt on first vote.
  voter_display_name TEXT,

  vote_type TEXT NOT NULL CHECK (vote_type IN ('up', 'down')),

  -- Optional free-text comment ("the museum closes early, swap it").
  comment TEXT,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- One vote per cookie per activity. Re-voting upserts on this constraint.
  UNIQUE (trip_id, activity_id, voter_cookie_id)
);

COMMENT ON TABLE public.anonymous_activity_votes IS
  'Thumbs up/down votes on shared trip activities from anonymous (un-signed-up) viewers. Dedupe by cookie id; one vote per activity per cookie.';

COMMENT ON COLUMN public.anonymous_activity_votes.activity_id IS
  'Per-activity nanoid from trips.itinerary JSONB — not a foreign key, just a string.';

COMMENT ON COLUMN public.anonymous_activity_votes.voter_cookie_id IS
  'Opaque httpOnly-cookie-issued id (mt_anon_voter). Best-effort dedupe — clearing cookies bypasses it.';

COMMENT ON COLUMN public.anonymous_activity_votes.share_token IS
  'The share token the voter used to reach the trip — audit trail only; API route validates token→trip mapping before INSERT.';

-- =====================================================
-- Indexes
-- =====================================================

-- Aggregation query: count up/down per activity for the current trip.
-- Powers the GET /api/shared/[token]/votes hydration call.
CREATE INDEX IF NOT EXISTS idx_anon_votes_trip_activity
  ON public.anonymous_activity_votes(trip_id, activity_id);

-- "Show me what THIS voter voted for" — fast cookie lookup per trip.
CREATE INDEX IF NOT EXISTS idx_anon_votes_trip_cookie
  ON public.anonymous_activity_votes(trip_id, voter_cookie_id);

-- =====================================================
-- updated_at trigger
-- =====================================================
-- Reuse the existing `update_proposal_updated_at` helper from the
-- 20251221_create_activity_proposals migration. It's a generic NEW.updated_at
-- = now() function — no proposal-specific logic.

CREATE TRIGGER trigger_anon_vote_updated_at
  BEFORE UPDATE ON public.anonymous_activity_votes
  FOR EACH ROW
  EXECUTE FUNCTION public.update_proposal_updated_at();

-- =====================================================
-- RLS
-- =====================================================
-- Vote tallies are public — the shared trip page itself is public, so anyone
-- with the URL can read the counts. Writes are blocked at the RLS layer and
-- only allowed via the service-role API route, which validates the share
-- token before accepting the upsert.

ALTER TABLE public.anonymous_activity_votes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read anonymous votes"
  ON public.anonymous_activity_votes
  FOR SELECT
  USING (true);

-- Note: no INSERT/UPDATE/DELETE policies. The anon and authenticated roles
-- have no write access. Service role bypasses RLS, which is what the API
-- route uses.
